// @ts-check
import js from "@eslint/js";
import { flatConfig as nextFlatConfig } from "@next/eslint-plugin-next";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import prettier from "eslint-plugin-prettier";
// @ts-ignore
import importPlugin from "eslint-plugin-import";
import globals from "globals";

/** @type {import('eslint').Linter.Config[]} */
export const baseConfig = [
  js.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        // tsconfig.json is solution-style (uses `references`), which
        // parserOptions.project can't resolve per-file; projectService
        // finds the right referenced tsconfig for each file instead.
        projectService: {
          allowDefaultProject: ["*.ts"],
        },
        tsconfigRootDir: import.meta.dirname,
        ecmaVersion: "latest",
        sourceType: "module",
      },
      globals: {
        ...globals.node,
        ...globals.browser,
        // Bun-specific globals
        Bun: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": tsPlugin,
      import: importPlugin,
      prettier: prettier,
    },
    settings: {
      "import/resolver": {
        "typescript-bun": {
          project: true,
          alwaysTryTypes: true,
        },
      },
      "import/core-modules": ["bun:test"],
    },
    rules: {
      // TypeScript rules
      ...tsPlugin.configs?.["strict"]?.rules,
      "@typescript-eslint/explicit-function-return-type": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/strict-boolean-expressions": "error",

      // Import rules
      "import/order": [
        "error",
        {
          groups: ["builtin", "external", "internal", "parent", "sibling", "index"],
          "newlines-between": "always",
          alphabetize: { order: "asc" },
        },
      ],
      "import/no-unresolved": ["error", { ignore: ["^/public/"] }],
      "import/no-cycle": "error",

      // General rules
      "no-console": ["warn", { allow: ["warn", "error", "info"] }],
      eqeqeq: ["error", "smart"],

      // Prettier rules
      "prettier/prettier": "error",
    },
  },
  {
    files: ["**/*.{ts,tsx}"],
    ...nextFlatConfig.coreWebVitals,
  },
  {
    // Unmodified shadcn/ui-generated primitives; these stylistic rules
    // don't fit code that's meant to be regenerated by the shadcn CLI.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/strict-boolean-expressions": "off",
    },
  },
];

export default baseConfig;
